---
title: "Untitled"
author: "Yu-Xiang, Lin"
date: "9/21/2020"
output:
  pdf_document: default
  html_document: default
---

```{r}

test <- data.frame(chest = c(34,37,38,36,38,43,40,38,40,41,
                     36,36,34,33,36,37,34,36,38,35),
           waist = c(30,32,30,33,29,32,33,30,30,32,
                     24,25,24,22,26,26,25,26,28,23),
           hips = c(32,37,36,39,33,38,42,40,37,39,
                    35,37,37,34,38,37,38,37,40,35),
           gender = c(rep("male",10),rep("female",10)))
```

```{r}
n1 <- 10; n2 <- 10; p <- 3

f_mat <- subset(test,gender=="female")[,1:3]
m_mat <- subset(test,gender == "male")[,1:3]
cov_pool <- ((cov(f_mat) * (n1-1)) + (cov(m_mat)* (n2-1))) / (n1+n2-2) ; 
cov_p_inv <- solve(cov_pool) ; cov_p_inv





f_m <- apply(subset(test,gender=="female")[,1:3],2,mean)
m_m <- apply(subset(test,gender=="male")[,1:3],2,mean)

T2 <- ((n1*n2)/(n1+n2)) * t(m_m - f_m) %*% cov_p_inv %*% (m_m-f_m)
F_calc <- (n1+n2-p-1)* T2/ ((n1+n2-2)*p)
df1 <- p; df2 <- n1+n2-p-1
F_calc > qf(0.95,df1, df2)

install.packages("Hotelling")
library(Hotelling)
library(corpcor)

fit = hotelling.test(data = test,.~gender);fit

install.packages("ICSNP")
library(ICSNP)
library(ICS)
library(mvtnorm)

```



```{r}
n1 = 3; n2 = 7; p = 3
test2 <- data.frame(teacher = rep(c(1,2),c(3,6)),satis = c(1,3,2,4,6,6,5,5,4),
           know = c(3,7,2,6,8,8,10,10,6))

HotellingsT2(cbind(test2$satis,test2$know)~test2$teacher)
```




```{r}
scale(HBAT$X7)
install.packages("car")
dataEllipse(test2$satis,test2$know,levels = c(0.025,0.975))
```

